version: '3.3'

services:
  tech-assesment:
    build:
      context: ./
      dockerfile: app.dockerfile
    restart: always
    ports:
      - "9000:80"
    depends_on:
      - database

  database:
    image: mysql:5.7
    restart: always
    ports:
      - "9001:3306"
    volumes:
      - schema:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER:          'tech-assesment'
      MYSQL_PASSWORD:      ''
      MYSQL_DATABASE:      'tech-assesment'

volumes:
  schema:
    driver: "local"
